spark:
  master: local[*]
  appName: javasparkexecutor
  kafka:
    checkPointLocation: /tmp
  defaultProperties:
    local:
      dir: /tmp
    driver:
      cores: 1
      maxResultSize: 1g
      memory: 1g
  streaming:
    query:
      timeOut: 1000000
    duration: 100000
  sql:
    warehouse:
      dir: /tmp
    shuffle:
      partitions: 10
kafka:
  topic: EmployeeData
  bootstrap:
    servers: 127.0.0.1:9092
  schema:
    registry:
      url: http:127.0.0.1:8081
  consumer:
    pollTimeOut: 1000
    startingOffsets: earliest
    failOnDataLoss: false